/* Project settings */
var hmForceRedirect = true;
var hmAnimate = true;
var hmPopupSticky = true;
var hmImageLightbox = true;
var hmVideoLightbox = true;
var hmLightboxConstrained = true;
var hmForceRedirect = true;
var hmTocSingleClick = true;
var autocollapse = false;
var gaaccount = "UA-486863-1";
var initialtocstate = "collapsed";
