<?php

// WARNING: DO NOT EDIT THIS FILE.
// This file is automatically generated by the Zoom Indexer application
// and will be updated each time you re-index your site. You should make all
// setting changes directly from the Indexer, via the Configuration window.
// 
// If you wish to modify the text messages such as "Search results for...",
// etc. then look up "Zoom Language Files" or "Translating the search page"
// in the Users Guide for information.

$UseUTF8 = 1;
$Charset = "UTF-8";
$UseStemming = 1;
$StemmingAlgo = 2;
$NoCharset = 0;
$MapAccents = 0;
$MinWordLen = 3;
$Highlighting = 1;
$GotoHighlight = 1;
$PdfHighlight = 1;
$FormFormat = 2;
$Logging = 0;
$LogFileName = "./logs/searchwords.log";
$MaxKeyWordLineLen = 256;
$OutputBasewordBufferSize = 13977;
$OutputVariantBufferSize = 2498;
$DictIDLen = 4;
$NumKeywords = 1055;
$NumVariants = 202;
$NumPages = 30;
$PageInfoSize = 510;
$MaxMatches = 1000;
$MaxContextSeeks = 500;
$MaxSearchTime = 30;
$DictReservedLimit = 165;
$DictReservedSuffixes = 83;
$DictReservedPrefixes = 124;
$DictReservedNoSpaces = 165;
$WordSplit = 1;
$ZoomInfo = 0;
$Timing = 0;
$DefaultToAnd = 1;
$SearchAsSubstring = 1;
$ToLowerSearchWords = 1;
$StripDiacritics = 0;
$ContextSize = 30;
$MaxContextKeywords = 3;
$WeightProximity = 0;
$AllowExactPhrase = 0;
$UseLinkTarget = 1;
$LinkTarget = "hmcontent";
$UseDateTime = 1;
$UseZoomImage = 0;
$WordJoinChars = ".-_'";
$Spelling = 0;
$Recommended = 0;
$NumRecommended = 0;
$RecommendedMax = 0;
$UseCats = 0;
$UseMetaFields = 0;
$NumMetaFields = 0;
$DisplayMetaFields = 0;
$TruncateShowURL = 0;
$DisplayNumber = 1;
$DisplayTitle = 1;
$DisplayMetaDesc = 1;
$DisplayContext = 0;
$DisplayTerms = 1;
$DisplayScore = 1;
$DisplayURL = 0;
$DisplayDate = 1;
$DisplayFilesize = 0;
$StartPtFailed = 0;
$Version = "Version 6.0.1015 (Custom for EC Software) PRO";
$STR_FORM_SEARCHFOR = "Search for:";
$STR_FORM_SUBMIT_BUTTON = "Submit";
$STR_FORM_RESULTS_PER_PAGE = "Results per page:";
$STR_FORM_MATCH = "Match:";
$STR_FORM_ANY_SEARCH_WORDS = "any words";
$STR_FORM_ALL_SEARCH_WORDS = "all words";
$STR_NO_QUERY = "No search query entered.";
$STR_RESULTS_FOR = "Search results for:";
$STR_NO_RESULTS = "No results";
$STR_RESULT = "result";
$STR_RESULTS = "results";
$STR_PHRASE_CONTAINS_COMMON_WORDS = "The following phrase contains very common words on this site, resulting in a limited search. Please define a more specific phrase for better results.";
$STR_SKIPPED_FOLLOWING_WORDS = "The following word(s) are in the skip word list and have been omitted from your search:";
$STR_SKIPPED_PHRASE = "Note that you can not search for exact phrases beginning with a skipped word";
$STR_SUMMARY_NO_RESULTS_FOUND = "No results found.";
$STR_SUMMARY_FOUND_CONTAINING_ALL_TERMS = "found containing all search terms.";
$STR_SUMMARY_FOUND_CONTAINING_SOME_TERMS = "found containing some search terms.";
$STR_SUMMARY_FOUND = "found.";
$STR_PAGES_OF_RESULTS = "pages of results.";
$STR_POSSIBLY_GET_MORE_RESULTS = "You can possibly get more results searching for";
$STR_ANY_OF_TERMS = "any of the terms";
$STR_DIDYOUMEAN = "Did you mean:";
$STR_SORTEDBY_RELEVANCE = "Sorted by relevance";
$STR_SORTBY_RELEVANCE = "Sort by relevance";
$STR_SORTBY_DATE = "Sort by date";
$STR_SORTEDBY_DATE = "Sorted by date";
$STR_RESULT_TERMS_MATCHED = "Terms matched:";
$STR_RESULT_SCORE = "Score:";
$STR_RESULT_URL = "URL:";
$STR_RESULT_PAGES = "Results Pages:";
$STR_RESULT_PAGES_PREVIOUS = "Previous";
$STR_RESULT_PAGES_NEXT = "Next";
$STR_FORM_CATEGORY = "Category:";
$STR_FORM_CATEGORY_ALL = "All";
$STR_RESULTS_IN_ALL_CATEGORIES = "in all categories";
$STR_RESULTS_IN_CATEGORY = "in category";
$STR_POWEREDBY = "Search powered by";
$STR_MORETHAN = "More than";
$STR_ALL_CATS = "all categories";
$STR_CAT_SUMMARY = "Refine your search by category:";
$STR_OR = "or";
$STR_RECOMMENDED = "Recommended links";
$STR_SEARCH_TOOK = "Search took";
$STR_SECONDS = "seconds";
$STR_MAX_RESULTS = "You have requested more results than served per query. Please try again with a more precise query.";
?>
