apiRules:
  - exclude:
      uidRegex: ^Fusee\.Example
      type: Type
  - exclude:
      uidRegex: ^Fusee\.Engine\.Imp\.Graphics\.Desktop\._3DconnexionDriver
      type: Type
  - exclude:
      uidRegex: ^Fusee\.Engine\.Imp\.Network\.Desktop
      type: Type
  - exclude:
      uidRegex: ^Fusee\.Engine\.Imp\.Physics\.Desktop
      type: Type
  - exclude:
      uidRegex: ^Fusee\.Engine\.Imp\.Sound\.Desktop
      type: Type
  - exclude:
      uidRegex: ^Fusee\.Engine\.Player
      type: Type
  - exclude:
      uidRegex: ^Fusee\.Tools
      type: Type
  - exclude:
      uidRegex: ^Fusee\.Test
      type: Type
  - exclude:
      uidRegex: _3DconnexionDriver$
      type: Type
