# This is a basic workflow to help you get started with Actions

name: Website build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2022

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Checkout submodules
        run: git submodule update --init --recursive
        
      - name: Update submodules
        run: git submodule update --recursive --remote

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Clearing docs directory
        run: |
          Remove-Item 'docs' -Recurse
          mkdir docs
          echo fusee3d.org > docs/CNAME

      - name: Create wiki toc.yml from _Sidebar.md
        run: bin\GitHubWikiSidbarToDocFX\GitHubWikiSidbarToDocFX.exe docfx_project\wiki\_Sidebar.md docfx_project\wiki

      - name: Build website
        run: bin\DocFX\docfx.exe docfx_project\docfx.json

      - name: Upload toc.yml artifact
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: toc.yml
          path: docfx_project\wiki\toc.yml

      - name: Commiting changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Website update
